apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-petclinic
  name: spring-petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-petclinic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: chielvis1/spring-petclinic
        name: spring-petclinic
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: spring-petclinic
